/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/assignments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for Assignment model. */
        get: operations["assignments_list"];
        put?: never;
        /** @description ViewSet for Assignment model. */
        post: operations["assignments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for Assignment model. */
        get: operations["assignments_retrieve"];
        /** @description ViewSet for Assignment model. */
        put: operations["assignments_update"];
        post?: never;
        /** @description ViewSet for Assignment model. */
        delete: operations["assignments_destroy"];
        options?: never;
        head?: never;
        /** @description ViewSet for Assignment model. */
        patch: operations["assignments_partial_update"];
        trace?: never;
    };
    "/api/assignments/{id}/mark_completed/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Mark assignment as completed. */
        post: operations["assignments_mark_completed_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/bootstrap/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Get role-aware auth bootstrap payload for shell routing.
         *
         *     GET /api/auth/bootstrap/
         */
        get: operations["auth_bootstrap_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Change password for authenticated user.
         *
         *     POST /api/auth/change-password/
         *     {
         *         "current_password": "MevcutSifre123",
         *         "new_password": "YeniSifre123",
         *         "new_password_confirm": "YeniSifre123"
         *     }
         */
        post: operations["auth_change_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/customer-profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get or update the authenticated customer profile. */
        get: operations["auth_customer_profile_retrieve"];
        /** @description Get or update the authenticated customer profile. */
        put: operations["auth_customer_profile_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Get or update the authenticated customer profile. */
        patch: operations["auth_customer_profile_partial_update"];
        trace?: never;
    };
    "/api/auth/forgot-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Request password reset code.
         *
         *     POST /api/auth/forgot-password/
         *     {
         *         "email": "email@example.com"
         *     }
         */
        post: operations["auth_forgot_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Google ID Token ile giriş/kayıt.
         *
         *     POST /api/auth/google/
         *     {
         *         "id_token": "google_id_token_string"
         *     }
         *
         *     Returns:
         *         - access: JWT access token
         *         - refresh: JWT refresh token
         *         - is_new_user: Yeni kullanıcı mı
         *         - user: Kullanıcı bilgileri
         */
        post: operations["auth_google_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Get/update authenticated user profile.
         *
         *     GET /api/auth/profile/
         *     PATCH /api/auth/profile/
         *     PUT /api/auth/profile/
         */
        get: operations["auth_profile_retrieve"];
        /**
         * @description Get/update authenticated user profile.
         *
         *     GET /api/auth/profile/
         *     PATCH /api/auth/profile/
         *     PUT /api/auth/profile/
         */
        put: operations["auth_profile_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Get/update authenticated user profile.
         *
         *     GET /api/auth/profile/
         *     PATCH /api/auth/profile/
         *     PUT /api/auth/profile/
         */
        patch: operations["auth_profile_partial_update"];
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Register a new user and send email verification code.
         *
         *     POST /api/auth/register/
         *     {
         *         "username": "kullanici_adi",
         *         "email": "email@example.com",
         *         "password": "Sifre123",
         *         "password_confirm": "Sifre123",
         *         "first_name": "Ad",
         *         "last_name": "Soyad"
         *     }
         */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register-device/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description FCM device token kaydet.
         *
         *     POST /api/auth/register-device/
         *     {
         *         "token": "fcm_device_token",
         *         "platform": "android" | "ios"
         *     }
         */
        post: operations["auth_register_device_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-verification/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Resend verification code to email.
         *
         *     POST /api/auth/resend-verification/
         *     {
         *         "email": "email@example.com"
         *     }
         */
        post: operations["auth_resend_verification_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Reset password with the 6-digit code.
         *
         *     POST /api/auth/reset-password/
         *     {
         *         "email": "email@example.com",
         *         "code": "123456",
         *         "new_password": "YeniSifre123",
         *         "new_password_confirm": "YeniSifre123"
         *     }
         */
        post: operations["auth_reset_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/teacher-profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get or update the authenticated teacher profile. */
        get: operations["auth_teacher_profile_retrieve"];
        /** @description Get or update the authenticated teacher profile. */
        put: operations["auth_teacher_profile_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Get or update the authenticated teacher profile. */
        patch: operations["auth_teacher_profile_partial_update"];
        trace?: never;
    };
    "/api/auth/verify-email/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Verify email with the 6-digit code.
         *
         *     POST /api/auth/verify-email/
         *     {
         *         "email": "email@example.com",
         *         "code": "123456"
         *     }
         */
        post: operations["auth_verify_email_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/detailed_stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get detailed statistics for dashboard. */
        get: operations["dashboard_detailed_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/earnings_report/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get earnings report (weekly, monthly, yearly). */
        get: operations["dashboard_earnings_report_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get basic dashboard statistics. */
        get: operations["dashboard_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/today_schedule/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get today's lesson schedule. */
        get: operations["dashboard_today_schedule_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/upcoming_lessons/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get upcoming lessons. */
        get: operations["dashboard_upcoming_lessons_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for Lesson model. */
        get: operations["lessons_list"];
        put?: never;
        /** @description Create a new lesson with conflict checking. */
        post: operations["lessons_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for Lesson model. */
        get: operations["lessons_retrieve"];
        /** @description Update a lesson with conflict checking. */
        put: operations["lessons_update"];
        post?: never;
        /** @description ViewSet for Lesson model. */
        delete: operations["lessons_destroy"];
        options?: never;
        head?: never;
        /** @description Partial update with conflict checking. */
        patch: operations["lessons_partial_update"];
        trace?: never;
    };
    "/api/lessons/{id}/cancel_with_reason/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Cancel lesson with a reason. */
        post: operations["lessons_cancel_with_reason_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{id}/mark_cancelled/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Mark lesson as cancelled. */
        post: operations["lessons_mark_cancelled_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{id}/mark_completed/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Mark lesson as completed. */
        post: operations["lessons_mark_completed_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{id}/mark_paid/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Mark lesson payment as paid. */
        post: operations["lessons_mark_paid_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{id}/quick_complete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Quick complete lesson with all related operations. */
        post: operations["lessons_quick_complete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{id}/update_schedule/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Update lesson schedule time. */
        post: operations["lessons_update_schedule_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/mark_all_pending_paid/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Mark all pending payments as paid. */
        post: operations["lessons_mark_all_pending_paid_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/mark_multiple_paid/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Mark multiple lessons as paid. */
        post: operations["lessons_mark_multiple_paid_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/pending_payments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get list of pending payments. */
        get: operations["lessons_pending_payments_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification-preferences/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Get or create the user's notification preferences.
         *
         *     Returns the current notification settings for the authenticated user.
         *     If no preferences exist, creates default preferences.
         */
        get: operations["notification_preferences_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Update the user's notification preferences.
         *
         *     Accepts partial updates - only fields that need to change.
         */
        patch: operations["notification_preferences_partial_update"];
        trace?: never;
    };
    "/api/notification-preferences/choices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Get available choices for reminder settings.
         *
         *     Returns the available options for minutes and days selections.
         */
        get: operations["notification_preferences_choices_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for Notification model. */
        get: operations["notifications_list"];
        put?: never;
        /** @description ViewSet for Notification model. */
        post: operations["notifications_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for Notification model. */
        get: operations["notifications_retrieve"];
        /** @description ViewSet for Notification model. */
        put: operations["notifications_update"];
        post?: never;
        /** @description ViewSet for Notification model. */
        delete: operations["notifications_destroy"];
        options?: never;
        head?: never;
        /** @description ViewSet for Notification model. */
        patch: operations["notifications_partial_update"];
        trace?: never;
    };
    "/api/notifications/{id}/mark_read/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Mark notification as read. */
        post: operations["notifications_mark_read_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/mark_all_read/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Mark all notifications as read. */
        post: operations["notifications_mark_all_read_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/pending_payments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Get pending payment information for notifications.
         *
         *     Returns students with pending lesson payments.
         */
        get: operations["notifications_pending_payments_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/unread_count/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get count of unread notifications. */
        get: operations["notifications_unread_count_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/upcoming_assignments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Get upcoming assignment due dates for notifications.
         *
         *     Returns assignments due in the next 7 days that are not completed.
         */
        get: operations["notifications_upcoming_assignments_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/upcoming_lessons/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Get upcoming lessons for notification scheduling.
         *
         *     Returns lessons for today and tomorrow that are not cancelled.
         */
        get: operations["notifications_upcoming_lessons_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for Schedule model. */
        get: operations["schedules_list"];
        put?: never;
        /** @description Create a new schedule with conflict checking. */
        post: operations["schedules_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for Schedule model. */
        get: operations["schedules_retrieve"];
        /** @description Update schedule with conflict checking. */
        put: operations["schedules_update"];
        post?: never;
        /** @description ViewSet for Schedule model. */
        delete: operations["schedules_destroy"];
        options?: never;
        head?: never;
        /** @description Partial update with conflict checking. */
        patch: operations["schedules_partial_update"];
        trace?: never;
    };
    "/api/schedules/weekly_schedule/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get weekly schedule starting from today for 7 days. */
        get: operations["schedules_weekly_schedule_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for Student model. */
        get: operations["students_list"];
        put?: never;
        /** @description ViewSet for Student model. */
        post: operations["students_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for Student model. */
        get: operations["students_retrieve"];
        /** @description ViewSet for Student model. */
        put: operations["students_update"];
        post?: never;
        /** @description ViewSet for Student model. */
        delete: operations["students_destroy"];
        options?: never;
        head?: never;
        /** @description ViewSet for Student model. */
        patch: operations["students_partial_update"];
        trace?: never;
    };
    "/api/students/{id}/statistics/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get statistics for a specific student. */
        get: operations["students_statistics_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Token view backed by the role-aware serializer. */
        post: operations["token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Serializer for Assignment model. */
        Assignment: {
            readonly id: number;
            readonly is_overdue: string;
            readonly student_name: string;
            readonly student_surname: string;
            book: string;
            topic: string;
            page: string;
            description?: string | null;
            is_completed?: boolean;
            /** Format: date */
            due_date?: string | null;
            /** Format: date */
            completion_date?: string | null;
            /** Format: date-time */
            readonly date_added: string;
            readonly teacher: number;
            student: number;
            lesson?: number | null;
        };
        /** @description Serializer for Assignment model. */
        AssignmentRequest: {
            book: string;
            topic: string;
            page: string;
            description?: string | null;
            is_completed?: boolean;
            /** Format: date */
            due_date?: string | null;
            /** Format: date */
            completion_date?: string | null;
            student: number;
            lesson?: number | null;
        };
        /** @enum {unknown} */
        BlankEnum: "";
        /**
         * @description * `monday` - Pazartesi
         *     * `tuesday` - Salı
         *     * `wednesday` - Çarşamba
         *     * `thursday` - Perşembe
         *     * `friday` - Cuma
         *     * `saturday` - Cumartesi
         *     * `sunday` - Pazar
         * @enum {string}
         */
        DayOfWeekEnum: "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";
        /** @description Serializer for Lesson model. */
        Lesson: {
            readonly id: number;
            readonly student_name: string;
            readonly student_surname: string;
            readonly parent_contact: string;
            readonly status_display: string;
            readonly payment_status_display: string;
            readonly lesson_type_display: string;
            readonly is_today: string;
            readonly is_upcoming: string;
            /** Format: date */
            date: string;
            /** Format: time */
            start_time: string;
            /** Format: time */
            end_time: string;
            lesson_type?: components["schemas"]["LessonTypeEnum"];
            status?: components["schemas"]["StatusEnum"];
            payment_status?: components["schemas"]["PaymentStatusEnum"];
            /** Format: decimal */
            lesson_fee: string;
            topic_covered?: string | null;
            book_progress?: string | null;
            notes?: string | null;
            cancel_reason?: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly teacher: number;
            student: number;
            schedule?: number | null;
        };
        /** @description Serializer for Lesson model. */
        LessonRequest: {
            /** Format: date */
            date: string;
            /** Format: time */
            start_time: string;
            /** Format: time */
            end_time: string;
            lesson_type?: components["schemas"]["LessonTypeEnum"];
            status?: components["schemas"]["StatusEnum"];
            payment_status?: components["schemas"]["PaymentStatusEnum"];
            /** Format: decimal */
            lesson_fee: string;
            topic_covered?: string | null;
            book_progress?: string | null;
            notes?: string | null;
            cancel_reason?: string | null;
            student: number;
            schedule?: number | null;
        };
        /**
         * @description * `online` - Online
         *     * `physical` - Yüz Yüze
         * @enum {string}
         */
        LessonTypeEnum: "online" | "physical";
        /**
         * @description * `beginner` - Başlangıç
         *     * `intermediate` - Orta
         *     * `advanced` - İleri
         * @enum {string}
         */
        LevelEnum: "beginner" | "intermediate" | "advanced";
        /** @description Serializer for Notification model. */
        Notification: {
            readonly id: number;
            readonly student_name: string;
            readonly student_surname: string;
            readonly notification_type_display: string;
            title: string;
            message: string;
            notification_type: components["schemas"]["NotificationTypeEnum"];
            is_read?: boolean;
            is_sent?: boolean;
            /** Format: date-time */
            send_at: string;
            /** Format: date-time */
            readonly created_at: string;
            readonly teacher: number;
            student?: number | null;
            lesson?: number | null;
        };
        /** @description Serializer for Notification model. */
        NotificationRequest: {
            title: string;
            message: string;
            notification_type: components["schemas"]["NotificationTypeEnum"];
            is_read?: boolean;
            is_sent?: boolean;
            /** Format: date-time */
            send_at: string;
            student?: number | null;
            lesson?: number | null;
        };
        /**
         * @description * `lesson_reminder` - Ders Hatırlatması
         *     * `payment_reminder` - Ödeme Hatırlatması
         *     * `assignment_reminder` - Ödev Hatırlatması
         *     * `general` - Genel
         * @enum {string}
         */
        NotificationTypeEnum: "lesson_reminder" | "payment_reminder" | "assignment_reminder" | "general";
        /** @enum {unknown} */
        NullEnum: null;
        /** @description Serializer for Assignment model. */
        PatchedAssignmentRequest: {
            book?: string;
            topic?: string;
            page?: string;
            description?: string | null;
            is_completed?: boolean;
            /** Format: date */
            due_date?: string | null;
            /** Format: date */
            completion_date?: string | null;
            student?: number;
            lesson?: number | null;
        };
        /** @description Serializer for Lesson model. */
        PatchedLessonRequest: {
            /** Format: date */
            date?: string;
            /** Format: time */
            start_time?: string;
            /** Format: time */
            end_time?: string;
            lesson_type?: components["schemas"]["LessonTypeEnum"];
            status?: components["schemas"]["StatusEnum"];
            payment_status?: components["schemas"]["PaymentStatusEnum"];
            /** Format: decimal */
            lesson_fee?: string;
            topic_covered?: string | null;
            book_progress?: string | null;
            notes?: string | null;
            cancel_reason?: string | null;
            student?: number;
            schedule?: number | null;
        };
        /** @description Serializer for Notification model. */
        PatchedNotificationRequest: {
            title?: string;
            message?: string;
            notification_type?: components["schemas"]["NotificationTypeEnum"];
            is_read?: boolean;
            is_sent?: boolean;
            /** Format: date-time */
            send_at?: string;
            student?: number | null;
            lesson?: number | null;
        };
        /** @description Serializer for Schedule model. */
        PatchedScheduleRequest: {
            day_of_week?: components["schemas"]["DayOfWeekEnum"];
            /** Format: time */
            start_time?: string;
            /** Format: time */
            end_time?: string;
            lesson_type?: components["schemas"]["LessonTypeEnum"];
            is_active?: boolean;
            /**
             * Format: date
             * @description İlk ders tarihi
             */
            first_lesson_date?: string | null;
            /**
             * Format: int64
             * @description Kaç haftalık ders planlanacak
             */
            weeks_duration?: number;
            student?: number;
        };
        /** @description Serializer for Student model. */
        PatchedStudentRequest: {
            name?: string;
            surname?: string;
            parent_name?: string;
            parent_contact?: string;
            grade?: string;
            school?: string;
            subject?: string;
            student_phone?: string | null;
            address?: string | null;
            /** Format: date */
            birth_date?: string | null;
            level?: (components["schemas"]["LevelEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            /** Format: decimal */
            lesson_fee?: string;
            last_topic?: string | null;
            book_progress?: string | null;
            /** Format: date */
            last_lesson_date?: string | null;
            notes?: string | null;
        };
        /**
         * @description * `pending` - Bekliyor
         *     * `paid` - Ödendi
         *     * `overdue` - Vadesi Geçti
         * @enum {string}
         */
        PaymentStatusEnum: "pending" | "paid" | "overdue";
        /** @description Include a safe user payload in the login response. */
        RoleAwareTokenObtainPairRequest: {
            username: string;
            password: string;
        };
        /** @description Serializer for Schedule model. */
        Schedule: {
            readonly id: number;
            readonly student_name: string;
            readonly student_surname: string;
            readonly day_of_week_display: string;
            readonly lesson_type_display: string;
            day_of_week: components["schemas"]["DayOfWeekEnum"];
            /** Format: time */
            start_time: string;
            /** Format: time */
            end_time: string;
            lesson_type?: components["schemas"]["LessonTypeEnum"];
            is_active?: boolean;
            /**
             * Format: date
             * @description İlk ders tarihi
             */
            first_lesson_date?: string | null;
            /**
             * Format: int64
             * @description Kaç haftalık ders planlanacak
             */
            weeks_duration?: number;
            /** Format: date-time */
            readonly created_at: string;
            readonly teacher: number;
            student: number;
        };
        /** @description Serializer for Schedule model. */
        ScheduleRequest: {
            day_of_week: components["schemas"]["DayOfWeekEnum"];
            /** Format: time */
            start_time: string;
            /** Format: time */
            end_time: string;
            lesson_type?: components["schemas"]["LessonTypeEnum"];
            is_active?: boolean;
            /**
             * Format: date
             * @description İlk ders tarihi
             */
            first_lesson_date?: string | null;
            /**
             * Format: int64
             * @description Kaç haftalık ders planlanacak
             */
            weeks_duration?: number;
            student: number;
        };
        /**
         * @description * `scheduled` - Planlandı
         *     * `completed` - Tamamlandı
         *     * `cancelled` - İptal Edildi
         *     * `missed` - Katılmadı
         * @enum {string}
         */
        StatusEnum: "scheduled" | "completed" | "cancelled" | "missed";
        /** @description Serializer for Student model. */
        Student: {
            readonly id: number;
            readonly assignment_completion_percentage: string;
            readonly total_lessons_count: string;
            readonly total_earned: string;
            readonly pending_payments: string;
            readonly debt_status: string;
            name: string;
            surname: string;
            parent_name: string;
            parent_contact: string;
            grade?: string;
            school?: string;
            subject?: string;
            student_phone?: string | null;
            address?: string | null;
            /** Format: date */
            birth_date?: string | null;
            level?: (components["schemas"]["LevelEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            /** Format: decimal */
            lesson_fee?: string;
            last_topic?: string | null;
            book_progress?: string | null;
            /** Format: date */
            last_lesson_date?: string | null;
            notes?: string | null;
            /** Format: date-time */
            readonly created_at: string;
            readonly teacher: number;
        };
        /** @description Serializer for Student model. */
        StudentRequest: {
            name: string;
            surname: string;
            parent_name: string;
            parent_contact: string;
            grade?: string;
            school?: string;
            subject?: string;
            student_phone?: string | null;
            address?: string | null;
            /** Format: date */
            birth_date?: string | null;
            level?: (components["schemas"]["LevelEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            /** Format: decimal */
            lesson_fee?: string;
            last_topic?: string | null;
            book_progress?: string | null;
            /** Format: date */
            last_lesson_date?: string | null;
            notes?: string | null;
        };
        TokenRefresh: {
            readonly access: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    assignments_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"][];
                };
            };
        };
    };
    assignments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AssignmentRequest"];
                "multipart/form-data": components["schemas"]["AssignmentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
        };
    };
    assignments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this assignment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
        };
    };
    assignments_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this assignment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AssignmentRequest"];
                "multipart/form-data": components["schemas"]["AssignmentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
        };
    };
    assignments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this assignment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    assignments_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this assignment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAssignmentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAssignmentRequest"];
                "multipart/form-data": components["schemas"]["PatchedAssignmentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
        };
    };
    assignments_mark_completed_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this assignment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AssignmentRequest"];
                "multipart/form-data": components["schemas"]["AssignmentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
        };
    };
    auth_bootstrap_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_change_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_customer_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_customer_profile_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_customer_profile_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_forgot_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_google_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_profile_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_profile_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register_device_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_resend_verification_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_reset_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_teacher_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_teacher_profile_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_teacher_profile_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_verify_email_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dashboard_detailed_stats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dashboard_earnings_report_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dashboard_stats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dashboard_today_schedule_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dashboard_upcoming_lessons_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    lessons_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"][];
                };
            };
        };
    };
    lessons_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LessonRequest"];
                "multipart/form-data": components["schemas"]["LessonRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
        };
    };
    lessons_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lesson. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
        };
    };
    lessons_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lesson. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LessonRequest"];
                "multipart/form-data": components["schemas"]["LessonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
        };
    };
    lessons_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lesson. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    lessons_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lesson. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedLessonRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedLessonRequest"];
                "multipart/form-data": components["schemas"]["PatchedLessonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
        };
    };
    lessons_cancel_with_reason_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lesson. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LessonRequest"];
                "multipart/form-data": components["schemas"]["LessonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
        };
    };
    lessons_mark_cancelled_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lesson. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LessonRequest"];
                "multipart/form-data": components["schemas"]["LessonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
        };
    };
    lessons_mark_completed_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lesson. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LessonRequest"];
                "multipart/form-data": components["schemas"]["LessonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
        };
    };
    lessons_mark_paid_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lesson. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LessonRequest"];
                "multipart/form-data": components["schemas"]["LessonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
        };
    };
    lessons_quick_complete_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lesson. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LessonRequest"];
                "multipart/form-data": components["schemas"]["LessonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
        };
    };
    lessons_update_schedule_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lesson. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LessonRequest"];
                "multipart/form-data": components["schemas"]["LessonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
        };
    };
    lessons_mark_all_pending_paid_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LessonRequest"];
                "multipart/form-data": components["schemas"]["LessonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
        };
    };
    lessons_mark_multiple_paid_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LessonRequest"];
                "multipart/form-data": components["schemas"]["LessonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
        };
    };
    lessons_pending_payments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
        };
    };
    notification_preferences_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    notification_preferences_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    notification_preferences_choices_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    notifications_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"][];
                };
            };
        };
    };
    notifications_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["NotificationRequest"];
                "multipart/form-data": components["schemas"]["NotificationRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    notifications_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this notification. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    notifications_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this notification. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["NotificationRequest"];
                "multipart/form-data": components["schemas"]["NotificationRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    notifications_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this notification. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    notifications_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this notification. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedNotificationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedNotificationRequest"];
                "multipart/form-data": components["schemas"]["PatchedNotificationRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    notifications_mark_read_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this notification. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["NotificationRequest"];
                "multipart/form-data": components["schemas"]["NotificationRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    notifications_mark_all_read_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["NotificationRequest"];
                "multipart/form-data": components["schemas"]["NotificationRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    notifications_pending_payments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    notifications_unread_count_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    notifications_upcoming_assignments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    notifications_upcoming_lessons_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    schedules_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"][];
                };
            };
        };
    };
    schedules_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ScheduleRequest"];
                "multipart/form-data": components["schemas"]["ScheduleRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
        };
    };
    schedules_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this schedule. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
        };
    };
    schedules_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this schedule. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ScheduleRequest"];
                "multipart/form-data": components["schemas"]["ScheduleRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
        };
    };
    schedules_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this schedule. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    schedules_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this schedule. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedScheduleRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedScheduleRequest"];
                "multipart/form-data": components["schemas"]["PatchedScheduleRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
        };
    };
    schedules_weekly_schedule_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
        };
    };
    students_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"][];
                };
            };
        };
    };
    students_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["StudentRequest"];
                "multipart/form-data": components["schemas"]["StudentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
        };
    };
    students_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
        };
    };
    students_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["StudentRequest"];
                "multipart/form-data": components["schemas"]["StudentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
        };
    };
    students_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    students_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedStudentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedStudentRequest"];
                "multipart/form-data": components["schemas"]["PatchedStudentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
        };
    };
    students_statistics_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
        };
    };
    token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleAwareTokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RoleAwareTokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["RoleAwareTokenObtainPairRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
}
